### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by leopoldhub** [confusinguser/minecraft-packet-proxy#2]
```
C:\Users\xxxxxxxx\Documents\MCProxy-master\minecraft-packet-proxy-master\node_modules\yggdrasil\lib\Client.js:37
            options.token = options.token ?? uuid_1.default.v4();
                                           ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Users\Burn\Documents\MCProxy-master\minecraft-packet-proxy-master\node_modules\yggdrasil\lib\index.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
```
need a specific node version?

**Comment by confusinguser** [comment]
Yes, you need at least node version 14. I would use the recommended version on [nodejs.org](nodejs)
